//=============================================================================
//
// file :        VacuumGauge.h
//
// description : Include for the VacuumGauge class.
//
// project :	TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :    European Synchrotron Radiation Facility
//               BP 220, Grenoble 38043
//               FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================
#ifndef _VACUUMGAUGE_H
#define _VACUUMGAUGE_H

#include <tango.h>
//using namespace Tango;

/**
 * @author	$Author:  $
 * @version	$Revision:  $
 */

 //	Add your own constants definitions here.
 //-----------------------------------------------


namespace VacuumGauge_ns
{

/**
 * Class Description:
 * Abstract Class for Vacuum Gauges
 */

/*
 *	Device States Description:
*  Tango::INIT :
*  Tango::ON :
*  Tango::ALARM :
*  Tango::FAULT :
*  Tango::DISABLE :
 */


class VacuumGauge: public Tango::Device_3Impl
{
public :
	//	Add your own data members here
	//-----------------------------------------


	//	Here is the Start of the automatic code generation part
	//-------------------------------------------------------------	
/**
 *	@name attributes
 *	Attributs member data.
 */
//@{
		Tango::DevDouble	*attr_Pressure_read;
//@}

/**
 *	@name Device properties
 *	Device properties member data.
 */
//@{
/**
 *	Gauge Controller used to read the gauge measure
 */
	string	gaugeController;
//@}

/**@name Constructors
 * Miscellaneous constructors */
//@{
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	VacuumGauge(Tango::DeviceClass *cl,string &s):Device_3Impl(cl,s) {};
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device Name
 */
	VacuumGauge(Tango::DeviceClass *cl,const char *s):Device_3Impl(cl,s) {};
/**
 * Constructs a newly allocated Command object.
 *
 *	@param cl	Class.
 *	@param s 	Device name
 *	@param d	Device description.
 */
	VacuumGauge(Tango::DeviceClass *cl,const char *s,const char *d):Device_3Impl(cl,s,d) {};
//@}

/**
 * @name VacuumGauge methods prototypes
 */

//@{
/**
 *	Hardware acquisition for attributes.
 */
	virtual void read_attr_hardware(vector<long> &attr_list) = 0;
/**
 *	Extract real attribute values for Pressure acquisition result.
 */
	virtual void read_Pressure(Tango::Attribute &attr) = 0;
/**
 *	Read/Write allowed for Pressure attribute.
 */
	virtual bool is_Pressure_allowed(Tango::AttReqType type){ return true; };

//@}

	//	Here is the end of the automatic code generation part
	//-------------------------------------------------------------	



protected :	
	//	Add your own data members here
	//-----------------------------------------
};

}	// namespace_ns

#endif	// _VACUUMGAUGE_H
