static const char *RcsId = "$Header:  $";
//+=============================================================================
//
// file :         VacuumGaugeStateMachine.cpp
//
// description :  C++ source for the VacuumGauge and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <VacuumGauge.h>
#include <VacuumGaugeClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace VacuumGauge_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		VacuumGauge::is_Pressure_allowed
// 
// description : 	Read/Write allowed for Pressure attribute.
//
//-----------------------------------------------------------------------------
bool VacuumGauge::is_Pressure_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================


}	// namespace VacuumGauge_ns
