//=============================================================================
//
// file :         VacuumGaugeClass.h
//
// description :  Include for the VacuumGaugeClass root class.
//                This class is represents the singleton class for
//                the VacuumGauge device class.
//                It contains all properties and methods which the 
//                VacuumGauge requires only once e.g. the commands.
//			
// project :      TANGO Device Server
//
// $Author:  $
//
// $Revision:  $
//
// $Log:  $
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#ifndef _VACUUMGAUGECLASS_H
#define _VACUUMGAUGECLASS_H

#include <tango.h>
#include <VacuumGauge.h>


namespace VacuumGauge_ns
{//=====================================
//	Define classes for attributes
//=====================================
class PressureAttrib: public Tango::Attr
{
public:
	PressureAttrib():Attr("Pressure", Tango::DEV_DOUBLE, Tango::READ) {};
	~PressureAttrib() {};
	
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
	{(static_cast<VacuumGauge *>(dev))->read_Pressure(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
	{return (static_cast<VacuumGauge *>(dev))->is_Pressure_allowed(ty);}
};

//=========================================
//	Define classes for commands
//=========================================
//
// The VacuumGaugeClass singleton definition
//

class VacuumGaugeClass : public Tango::DeviceClass
{
public:
//	properties member data

//	add your own data members here
//------------------------------------

public:

protected:
	VacuumGaugeClass(string &);
	void command_factory();
	void get_class_property();
	void attribute_factory(vector<Tango::Attr *> &);

private:
};


}	//	namespace VacuumGauge_ns

#endif // _VACUUMGAUGECLASS_H
